true;
false;
();
4269 * 9;
"hello";
let arc = "monke";
arc;
let a = fn() {};
b = "hi";
pp = ["hi", b, c];
{a:b, c:d};
if(a) { b;} else if (c) {d;} else {e;};
a();
b(a,b,c);
b(a, a, a)(c,c,c);
pp["hello"];
pp.temp;
pp.temp["hi"](a);
if(a == b) { a = a + 4;} else {b - 23; };